### ISSUE TITLE
您的 Bot 似乎不太智能

### ISSUE THREAD

**Issue by QYG2297248353** [Anyexyz/1panel-wiki#1]
https://github.com/Anyexyz/1panel-wiki/commit/3cb0b3cc6f2147a27f1389cab59dac26ba45190e

**Comment by Anyexyz** [comment]
可以根据贵站的需求定制应用更新脚本

**Comment by QYG2297248353** [comment]
https://github.com/Anyexyz/1panel-wiki/pull/2

我尝试进行了修复，本地测试已通过
